name: setup-env
description: "Setup environment"

runs:
  using: composite

  steps:
    - name: Setup mise and install tools
      uses: jdx/mise-action@b7800bbdc86cc07cbd08204366859657ca5bd6f0
      with:
        install: true

    - name: Install node modules
      shell: bash
      run: npm clean-install

    - name: Setup Python virtual environment
      shell: bash
      run: uv venv

    - name: Install python dependencies
      shell: bash
      run: pip install -r requirements.txt
